name: Create Release

on:
  push:
    tags:  
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Zip
        run: zip -r release.zip . -x ".git/*" ".github/*" ".gitignore" "README.md"
